# -*- coding: utf-8 -*-
"""Programación.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ptxi4WUJp1kXDvQrNcCbV2euBFirbkLC
"""

!pip install pyautocad

!pip install CAD

!pip install basemap

!pip install mpl_toolkits.basemap

!pip install map

!pip install folium

import pandas as pd
import matplotlib.pyplot as plt 
topografy='topogigio.xlsx'
df= pd.read_excel(topografy)
print(df.head())

import pandas as pd #modulo Pandas para lectura de diferente tipos de archivos
import numpy as np #modulo numpy, para manejo de arreglos y matrices
import folium as fl 
import matplotlib.pyplot as plt


#Extracción de datos de un archivo excel
datos = pd.read_excel ('topogigio.xlsx', usecols=(1,2,3,4), skiprows=(0),dtype=float, sheet_name=0) 
#Se hace lectura de un archivo xlsx, pero puede ser otro tipo de archivos como csv o txt, puedes leer la documentación adecuada
#sobre como extraer este tipo de archivos, así mismo existen foros donde ya vienen bloques programados para leer archivos
#el primer atributo es el nombre, se inserta como sting y en caso de que se encuentre en otro carpeta se debe poner la ruta a la
#carpeta
#el segundo atributo es sobre las columnas del archivo que se usarán
#el tercer atributo es para saltar filas, en este caso se omite la primera fila que es de encabezados
#el cuarto atributo es el ínidce de la hoja a usar, 0 para la primera
datos = datos.values #convierte del formato de pandas a un arreglo

ndp = len(datos) #se obtiene el número de lecturas

datos[0,1] = datos[0,3]+datos[0,0] #el formato "nan" es problemático, por lo que se hace que este valor sea 0 para la altura de aparato en 
#primera fila

for i in range (1,ndp): #se omite la primera fila de la tabla y se sigue hasta la última
    datos[i,3] = datos[i-1,1] - datos[i,2] # se saca la cota del punto de liga
    datos[i,1] = datos[i,3]+datos[i,0] # se obtiene la altura de aparato
    
desnivel = np.sum(datos[:,0])-np.sum(datos[:,2]) # se obtiene el desnivel

import csv
with open('outfile.txt', 'w') as f:
    csv.writer(f, delimiter=' ').writerows(datos)

print("Desnivel = %.3f m" %(abs(desnivel)))                         
print(datos)

import pandas as pd 
import numpy as np
import folium as fl 
import matplotlib.pyplot as plt

mapa=fl.Map()
mapa

mGye=fl.Map(location=[19.210330,-103.802482],width="60%",height="60%", zoom_start=25)
fl.Marker(location=[19.210330,-103.802482]).add_to(mGye)
fl.Marker(location=[19.210330,-103.802482],popup="Este punto marca donde se hizo la nivelación").add_to(mGye)
mGye